### ISSUE TITLE
Dynamic routes and other tabs within a sheet

### ISSUE THREAD

**Issue by codysaylor** [spenwall/gridsome-source-google-sheets#1]
Hi, I was wondering how I could define a dynamic route using this plugin. When I create GoogleSheet.vue in /templates it says that a path needs defined, but I'm not sure how this should be setup. Any insight is appreciated.

Also, is it possible to get information from another tab from within a single sheet?

Thanks for creating this plugin!

**Comment by spenwall** [comment]
Unfortunately this plugin can't be used in templates at this time and can only be queried in the pages components. Also, at this time it can only query the first sheet. 

I will need to set up an optional routes that the user can define because the data is so dynamic. However I really like this idea and I think I will work on it this week. Also open to pull requests if you are interested.

**Comment by codysaylor** [comment]
Ah yeah that makes sense. I briefly looked into how the routes are defined but no luck - ideally define the slug or path in a column or use the column id and define it in config.

That's awesome man! I really look forward to this feature (primarily dynamic routes) and if I get some time will see if I can help out.

**Comment by spenwall** [comment]
I have added a route option to 0.2.0 

Please let me know if it works for you or if you have any question.

**Comment by codysaylor** [comment]
This works great. Thanks so much!
